### ISSUE TITLE
Supported browsers?

### ISSUE THREAD

**Issue by mindplay-dk** [miguelmota/Navigator.sendBeacon#26]
Which browsers are supported by this polyfill?

(Probably should be explained in the README? 🙂)

**Comment by kronicker** [comment]
Hey, this polyfill checks if browser has native implemented navigator#sendBeacon and if not uses XHR instead. Since no advanced XHR features are used it should work properly in any browser that supports XHR.
List of browsers with native support (where this polyfill will basically be noop) can be found on [caniuse.com](https://caniuse.com/?search=Sendbeacon).

**Comment by mindplay-dk** [comment]
That tells me which browser might need the polyfill - but it doesn't tell me which browsers it will actually work on. Seems pretty important? Most projects target a specific set of browsers, so an author will want to know if this polyfill is going to work or not.
