### ISSUE TITLE
Consider using XMLHttpRequest.timeout

### ISSUE THREAD

**Issue by MorrisJohns** [miguelmota/Navigator.sendBeacon#5]
A synchronous request can "hang" some browsers if the connection is timing out. You should be able to set a timeout so that the request won't hang (although I admit I haven't tried it in beforeunload/unload events!).

You mostly need your fallback for IE and Safari:

IE: timeout property is supported since at least IE8 - see https://msdn.microsoft.com/en-us/library/cc304105(v=vs.85).aspx

Safari: timeout property is supported since Safari 6.1 - see Note 2 and Show all for http://caniuse.com/#search=XMLHttpRequest%20advanced%20features

Cheers

**Comment by miguelmota** [comment]
@MorrisJohns what are your thoughts on how the timeout should be set?

**Comment by MorrisJohns** [comment]
Comments about using synchronous XHR say that it delays the browser from loading the next page. If your users are on the same continent as your server, 1 second should be enough. I wouldn't want to go much over that (since if you are hitting the limit, you are most likely just affecting navigation within your own site)

**Comment by hax** [comment]
1 second seems too long in most cases, I suggest use a short number like 200ms by default.

**Comment by miguelmota** [comment]
Happy to merge in a PR if someone wants to take care of the timeout

**Comment by nateweiss** [comment]
Hi, curious if a PR for this issue is still desired/welcome. I'm thinking a default of something like 200ms as @hax suggested (or maybe 250?), which can be overridden by setting a number on the object itself, something like:

`navigator.sendBeacon.timeout = 500 // let it wait longer`

or, perhaps we don't like to add a public property since this is a polyfill. Maybe instead we support a global variable on the navigator object, something like this or similar:

`navigator._sendBeaconTimeout = 500`

**Comment by miguelmota** [comment]
setting `xhr.timeout` throws error `Timeouts cannot be set for synchronous requests made from a document.` so what I did is implement `setTimeout` and call `xhr.abort` if request is not yet complete.

```javascript
sendBeacon(url, data, {timeout: 250}); // ms
```

Please re-open issue if this doesn't suffice. Thanks!

**Comment by schmod** [comment]
Will this actually work?  If the request is synchronous, how would we ever reach the block of code that aborts the XHR?

**Comment by artz** [comment]
I too was looking for a timeout in the fallback solution here for Safari.  Because the synchronous XHR effectively blocks the event loop, `xhr.abort()` is invoked after the response is received regardless of the `setTimeout`.

[https://jsfiddle.net/e7ovu5to/4/](https://jsfiddle.net/e7ovu5to/4/)

Anyone solve this?

**Comment by miguelmota** [comment]
@schmod @artz ah good point. Looks like it might not be possible then

**Comment by miguelmota** [comment]
Closing this issue since it looks like it might not be possible to add a timeout to a synchronous call.

If someone has a good solution please re-open.
